// Renders docs/configuration.md from the settings registry (spec §14.4).
//   pnpm docs:config          write the file
//   pnpm docs:config --check  exit 1 if the committed file is stale (CI)
import { readFileSync, writeFileSync } from "node:fs";
import { GROUPS, SETTINGS, LLM_PRESETS, LLM_PROVIDERS } from "../src/lib/config/registry";

const OUT = "docs/configuration.md";

const BOOTSTRAP: { name: string; required: string; meaning: string }[] = [
  { name: "DATABASE_URL", required: "yes", meaning: "Postgres connection string (`postgres://…`). docker compose sets it for you." },
  { name: "AUTH_SECRET", required: "yes", meaning: "Session-signing secret, at least 32 characters (`openssl rand -base64 32`). Also derives the key that encrypts integration secrets at rest." },
  { name: "APP_URL", required: "recommended", meaning: "Public URL of this install. Used for the Google OAuth redirect, links in emails, and as the auth base URL. Also settable in Settings → Integrations → App." },
  { name: "ENCRYPTION_KEY", required: "no", meaning: "32-byte base64 key for encrypting integration secrets, instead of the key derived from `AUTH_SECRET`. Set it before the first secret is saved, or re-enter secrets after rotating." },
  { name: "DEMO_MODE", required: "no", meaning: "`true` boots the read-only demo with two synthetic sites and refuses every write." },
  { name: "TRUSTED_PROXY_HOPS", required: "no", meaning: "How many reverse proxies append to `X-Forwarded-For` (default 1). Used only to pick the client address for login rate limiting." },
];

const cell = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

export function renderConfigDocs(): string {
  const lines: string[] = [];
  lines.push("# Configuration", "", "<!-- Generated by scripts/gen-config-docs.ts from src/lib/config/registry.ts — do not edit by hand. -->", "");
  lines.push("Better Search Lab needs two environment variables to boot. Everything else is configured in the app under **Settings → Integrations**, and every one of those settings can also be supplied as an environment variable — when both are set, **the environment wins** and the field shows as read-only in the app.", "");
  lines.push("## Bootstrap environment", "", "| Variable | Required | Meaning |", "|---|---|---|");
  for (const b of BOOTSTRAP) lines.push(`| \`${b.name}\` | ${b.required} | ${cell(b.meaning)} |`);
  lines.push("");
  lines.push("## Integrations", "", "Each table lists the in-app field, the environment variable that overrides it, and older variable names that are still honoured so an existing `.env` keeps working.", "");
  for (const g of GROUPS.filter((x) => !x.hidden)) {
    lines.push(`### ${g.label}`, "", cell(g.description), "", "| Setting | Environment variable | Legacy names | Secret | Description |", "|---|---|---|---|---|");
    for (const s of SETTINGS.filter((x) => x.group === g.id)) {
      const opts = s.options ? ` One of: ${s.options.map((o) => `\`${o}\``).join(", ")}.` : "";
      lines.push(`| ${cell(s.label)} | \`${s.env}\` | ${s.legacyEnv?.map((n) => `\`${n}\``).join(", ") ?? "—"} | ${s.secret ? "yes" : "no"} | ${cell(s.description)}${opts} |`);
    }
    lines.push("");
  }
  lines.push("## AI assistant presets", "", "Choosing a provider fills the base URL and a default model; both stay editable.", "", "| Provider | Base URL | Default model | Needs a key |", "|---|---|---|---|");
  for (const id of LLM_PROVIDERS) { const p = LLM_PRESETS[id]; lines.push(`| ${p.label} (\`${id}\`) | ${p.baseUrl ? `\`${p.baseUrl}\`` : "—"} | ${p.defaultModel ? `\`${p.defaultModel}\`` : "—"} | ${p.needsKey ? "yes" : "no"} |`); }
  lines.push("");
  return lines.join("\n");
}

const isMain = process.argv[1]?.endsWith("gen-config-docs.ts");
if (isMain) {
  const rendered = renderConfigDocs();
  if (process.argv.includes("--check")) {
    let current = "";
    try { current = readFileSync(OUT, "utf8"); } catch { /* missing counts as stale */ }
    if (current !== rendered) { console.error(`${OUT} is stale — run: pnpm docs:config`); process.exit(1); }
    console.log(`${OUT} is up to date`);
  } else {
    writeFileSync(OUT, rendered);
    console.log(`wrote ${OUT}`);
  }
}
